MenedzerZarzadzaniaLotami/Controllers/SamolotEdytujController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProjektObiektowe.Models;

namespace ProjektObiektowe.Controllers
{
    public class SamolotEdytujController : Controller
    {
        private readonly SamolotContext _context;

        public SamolotEdytujController(SamolotContext context)
        {
            _context = context;
        }

        [HttpGet]
        public async Task<IActionResult> EdytujSamolot(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var samolot = await _context.Samoloty.FindAsync(id);
            if (samolot == null)
            {
                return NotFound();
            }

            var associatedFlights = await _context.Loty.AnyAsync(l => l.Id_Samolot == id);
            if (associatedFlights)
            {
                return RedirectToAction("BladEdycji");
            }

            return View(samolot);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EdytujSamolot(int id, [Bind("Id,Numer,Marka,Model,Rzedy_Klasa_1,Rzedy_Klasa_2,Linia")] Samolot samolot)
        {
            if (id != samolot.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    samolot.Pojemnosc = samolot.Rzedy_Klasa_1*4 + samolot.Rzedy_Klasa_2*6;
                    _context.Update(samolot);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SamolotExists(samolot.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index", "SamolotIndex");
            }
            return View(samolot);
        }

        private bool SamolotExists(int id)
        {
            return _context.Samoloty.Any(e => e.Id == id);
        }

        [HttpGet]
        public IActionResult BladEdycji()
        {
            return View();
        }
    }
}

MenedzerZarzadzaniaLotami/Views/SamolotEdytuj/BladEdycji.cshtml
<h3>Nie można edytwać samolotu, ponieważ istnieją przypisane do niego loty.</h3>

<a asp-action="Index" asp-controller="SamolotIndex" class="btn btn-secondary">Powrót do listy samolotów</a>

MenedzerZarzadzaniaLotami/Views/SamolotEdytuj/EdytujSamolot.cshtml
@model ProjektObiektowe.Models.Samolot

@{
    ViewData["Title"] = "Edytuj Samolot";
}

<h2>Edytuj dane samolotu</h2>

<form asp-action="EdytujSamolot" asp-controller="SamolotEdytuj" method="post">
    <input type="hidden" asp-for="Id" />

    <div class="form-group">
        <label asp-for="Numer" class="control-label">Numer Samolotu:</label>
        <input asp-for="Numer" class="form-control" />
        <span asp-validation-for="Numer" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Marka" class="control-label">Marka:</label>
        <input asp-for="Marka" class="form-control" />
        <span asp-validation-for="Marka" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Model" class="control-label">Model:</label>
        <input asp-for="Model" class="form-control" />
        <span asp-validation-for="Model" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Linia" class="control-label">Linia:</label>
        <input asp-for="Linia" class="form-control" />
        <span asp-validation-for="Linia" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Rzedy_Klasa_1" class="control-label">Liczba rzędów klasy 1:</label>
        <input asp-for="Rzedy_Klasa_1" class="form-control" />
        <span asp-validation-for="Rzedy_Klasa_1" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Rzedy_Klasa_2" class="control-label">Liczba rzędów klasy 2:</label>
        <input asp-for="Rzedy_Klasa_2" class="form-control" />
        <span asp-validation-for="Rzedy_Klasa_2" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-primary">Zapisz zmiany</button>
</form>

<p>
    <a asp-action="Index" asp-controller="SamolotIndex" class="btn btn-secondary">Anuluj</a>
</p>