MenedzerZarzadzaniaLotami/Controllers/SamolotDodajController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProjektObiektowe.Models;

namespace ProjektObiektowe.Controllers
{
    public class SamolotDodajController : Controller
    {
        private readonly SamolotContext _context;

        public SamolotDodajController(SamolotContext context)
        {
            _context = context;
        }

        [HttpGet]
        public IActionResult DodajSamolot()
        {
            return View(new Samolot());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DodajSamolot([Bind("Numer,Marka,Model,Rzedy_Klasa_1,Rzedy_Klasa_2,Linia")] Samolot samolot)
        {
            if (ModelState.IsValid)
            {
                var existingSamolot = await _context.Samoloty.FirstOrDefaultAsync(s => s.Numer == samolot.Numer);

                if (existingSamolot != null)
                {
                    ModelState.AddModelError("Numer", "Samolot o podanym numerze już istnieje.");
                    return View(samolot);
                }

                samolot.Pojemnosc = samolot.Rzedy_Klasa_1*4 + samolot.Rzedy_Klasa_2*6;
                _context.Add(samolot);
                await _context.SaveChangesAsync();

                return RedirectToAction("Index", "SamolotIndex");
            }

            return View(samolot);
        }
    }
}

MenedzerZarzadzaniaLotami/Controllers/SamolotIndexController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProjektObiektowe.Models;

namespace ProjektObiektowe.Controllers
{
    public class SamolotIndexController : Controller
    {
        private readonly SamolotContext _context;

        public SamolotIndexController(SamolotContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _context.Samoloty.ToListAsync());
        }

        public async Task<IActionResult> WybierzSamolot()
        {
            var samoloty = await _context.Samoloty.ToListAsync();
            return View(samoloty);
        }
    }
}

MenedzerZarzadzaniaLotami/Controllers/SamolotUsunController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProjektObiektowe.Models;

namespace ProjektObiektowe.Controllers
{
    public class SamolotUsunController : Controller
    {
        private readonly SamolotContext _context;

        public SamolotUsunController(SamolotContext context)
        {
            _context = context;
        }

        [HttpGet]
        public async Task<IActionResult> UsunSamolot(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var samolot = await _context.Samoloty.FirstOrDefaultAsync(m => m.Id == id);
            if (samolot == null)
            {
                return NotFound();
            }

            return View(samolot);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UsunSamolot(int id)
        {
            var samolot = await _context.Samoloty.FindAsync(id);

            var associatedFlights = await _context.Loty.AnyAsync(l => l.Id_Samolot == id);
            if (associatedFlights)
            {
                return RedirectToAction("BladUsuwania");
            }

            _context.Samoloty.Remove(samolot);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index", "SamolotIndex");
        }

        [HttpGet]
        public IActionResult BladUsuwania()
        {
            return View();
        }
    }
}

MenedzerZarzadzaniaLotami/Views/SamolotIndex/Index.cshtml
@model IEnumerable<ProjektObiektowe.Models.Samolot>

<p>
    <a asp-action="DodajSamolot" asp-controller="SamolotDodaj" class="btn btn-primary">Dodaj nowy samolot</a>

</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Marka)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Model)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Numer)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Pojemnosc)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Rzedy_Klasa_1)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Rzedy_Klasa_2)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Linia)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Marka)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Model)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Numer)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Pojemnosc)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Rzedy_Klasa_1)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Rzedy_Klasa_2)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Linia)
                </td>
                <td>
                    <a asp-action="EdytujSamolot" asp-controller="SamolotEdytuj" asp-route-id="@item.Id">Edytuj</a> |
                    <a asp-action="UsunSamolot" asp-controller="SamolotUsun" asp-route-id="@item.Id">Usuń</a>
                </td>
            </tr>
        }
    </tbody>
</table>