MenedzerZarzadzaniaLotami/Controllers/LotniskoDodajController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProjektObiektowe.Models;
using System.Threading.Tasks;

public class LotniskoDodajController : Controller
{
    private readonly BiletContext _context;

    public LotniskoDodajController(BiletContext context)
    {
        _context = context;
    }

    public IActionResult DodajLotnisko()
    {
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DodajLotnisko([Bind("Kod,Nazwa,Miasto,Kraj")] Lotnisko lotnisko)
    {
        if (ModelState.IsValid)
        {
            _context.Add(lotnisko);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index", "LotniskoIndex");
        }
        return View(lotnisko);
    }
}

MenedzerZarzadzaniaLotami/Views/LotniskoDodaj/DodajLotnisko.cshtml
@model ProjektObiektowe.Models.Lotnisko

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="DodajLotnisko" asp-controller="LotniskoDodaj">
            <div class="form-group">
                <label asp-for="Kod" class="control-label"></label>
                <input asp-for="Kod" class="form-control" />
                <span asp-validation-for="Kod" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nazwa" class="control-label"></label>
                <input asp-for="Nazwa" class="form-control" />
                <span asp-validation-for="Nazwa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Miasto" class="control-label"></label>
                <input asp-for="Miasto" class="form-control" />
                <span asp-validation-for="Miasto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Kraj" class="control-label"></label>
                <input asp-for="Kraj" class="form-control" />
                <span asp-validation-for="Kraj" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Dodaj lotnisko" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" asp-controller="LotniskoIndex">Anuluj</a>
</div>